### ISSUE TITLE
Single-run or constantly running?

### ISSUE THREAD

**Issue by fakebenjay** [freedomofpress/trackthenews#19]
This is less of an issue and more of a question, but is this script designed to run in the background indefinitely (in a way that could, say, power a Twitter bot,) or is it set up to run through all of the RSS feeds in `rssfeeds.json` just once? If it's the latter, how would you go about running this permanently as a background process so it can tweet indefinitely? Thanks!

**Comment by thisisparker** [comment]
Great question, and this could be better documented. It is designed to be run repeatedly. I have set [FOIAFeed](https://twitter.com/foiafeed) up on a cronjob that runs every 10 minutes, which works very well for my purposes. (In my case, it's enough time for there to be some new entries in the feed, but not the tweets are still timely and it doesn't take too long to run.) Other installs have wrapper scripts that start it running again as soon as it has stopped running.

You could choose to run it just once, say if you were dealing with "feeds" that were mostly static and just wanted to post a collection of tweets about them once. But yeah, I've made the assumption that you're going to be running it over and over, which is why the database keeps track of which articles you've already reviewed.

**Comment by fakebenjay** [comment]
What does that cronjob script look like?

**Comment by thisisparker** [comment]
All good? Do you think I should add this to the documentation? (It feels slightly out of scope, but if you think it'd be helpful we can open an issue and I can write it into the readme.)
